services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "webchat"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  chat-app:
    container_name: chat-app
    build: .
    ports:
      - "8081:8081"
    depends_on:
    - postgres
    env_file: .env
volumes:
  pgdata: