server:
  port: 8081

spring:
  application:
    name: "chat-client"
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "440439735116-osh21lackvhj4o21c8ne05hk7vmdokkl.apps.googleusercontent.com"
            clientSecret: "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"

app:
  input:
    wsUrl: "ws://localhost:8080/ws"
    serverUrl: "http://localhost:8080"
    subscribeDestination: "/topic/messages"
    publishDestination: "/app/chat"
    page: 0
    size: 5
